general {
    gaps_in = 5
    gaps_out = 10
    border_size = 0
    layout = dwindle
    resize_on_border = false
}

decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 0.8

    blur {
        enabled = true
        size = 5
        passes = 3
    }

    shadow {
        enabled = false
    }
}

animations {
    enabled = true

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    bezier = been, 0.24, 0.9, 0.25, 0.91
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = slow, 0, 0.85, 0.3, 1
    bezier = overshot, 0.7, 0.6, 0.1, 1.1
    bezier = bounce, 1.1, 1.6, 0.1, 0.85
    bezier = linear, 0, 0, 1, 1

    animation = windowsIn, 1, 5, slow, popin
    animation = windowsOut, 1, 7, been, popin 70%
    animation = windowsMove, 1, 5, wind, slide
    animation = border, 1, 1, linear
    animation = fade, 1, 5, overshot
    animation = workspaces, 1, 5, wind
    animation = windows, 1, 5, bounce, popin
}

windowrulev2 = opacity 0.90 0.90,class:^(ghostty)$
windowrulev2 = opacity 0.90 0.70 1.0,class:^(zen)$
windowrulev2 = opacity 0.85 0.70 1.0,class:^(discord)$
windowrulev2 = opacity 0.80 0.60 1.0,class:^(Spotify)$
